### ISSUE TITLE
Keyword is not valid as an identifier

### ISSUE THREAD

**Issue by JohnDovey** [juanruiz85/TELEGRAM_BOT_CONSOLE_VB.NET#1]
![image](https://user-images.githubusercontent.com/11061221/124322653-72ca0280-db45-11eb-947c-fdafbd5fb61e.png)

It doesn't like the "and" keyword

**Comment by JohnDovey** [comment]
Sorry. I see that was a problem introduced by Google translating the code (e = and)

**Comment by kaelco** [comment]
![Capture](https://user-images.githubusercontent.com/43575735/146353091-29c87dbf-9ae8-4d73-b3d6-84817a99f0cc.PNG)
I just put my token and giveme that error, what can be?
thank you
